---
title: "Project_3"
author: "Guangyu Qiu"
date: "2026-04-01"
output: pdf_document
---

```{r}
library(readr)
library(powertools)
library(tidyverse)
library(survival)
library(survminer)

cross_data <- read_csv("CrossData.csv")
cross_data
```


```{r}
fit_km <- survfit(Surv(time, status) ~ group, data = cross_data)

ggsurvplot(
  fit_km,
  data = cross_data,
  risk.table = TRUE, 
  pval = TRUE,
  conf.int = FALSE,
  legend.title = "Group",
  legend.labs = c("Control", "Treatment")
)
```
```{r}
p <- ggsurvplot(
  fit_km,
  data = cross_data,
  fun = "cloglog",
  conf.int = FALSE,
  legend.title = "Group"
)

p$plot + scale_x_log10()
```

```{r}
fit_cox <- coxph(Surv(time, status) ~ group, data = cross_data)

summary(fit_cox)
```

```{r}
test_ph <- cox.zph(fit_cox)

print(test_ph)
```
```{r}
ggcoxzph(test_ph)
```

```{r}
fit_cox_tt <- coxph(
  Surv(time, status) ~ group + tt(group),
  data = cross_data,
  tt = function(x, t, ...) x * t
)

summary(fit_cox_tt)
```
```{r}
fit_cox_tt <- coxph(
  Surv(time, status) ~ group + tt(group),
  data = cross_data,
  tt = function(x, t, ...) x * log (t)
)

summary(fit_cox_tt)
```


```{r}
fit_cox_discrete <- coxph(
  Surv(time, status) ~ group + tt(group),
  data = cross_data,
  tt = function(x, t, ...) {x * t>1.5}
)

summary(fit_cox_discrete)
```

