---
title: "Project0"
author: "Guangyu Qiu"
date: "2026-01-26"
# output: pdf_document
---
```{r}
library(tidyverse)
library(lme4)
library(lmerTest)
library(mgcv)
```


```{r}
data <- read.csv("Project0_Clean_v2.csv") %>%
  transmute(
    id = SubjectID,
    day = DAYNUMB, # day number: should be 1 - 3
    sample = Collection.Sample, # sample number of a day: 1 - 4
    sleep = Sleep.Diary.reported.wake.time, 
    # time
    booklet = if_else(sample == 1, 0,
      Booklet..Sample.interval.Decimal.Time..mins.),
    cap = if_else(sample == 1, 0,
      MEMs..Sample.interval.Decimal.Time..mins.),
    # outcome
    cortisol = Cortisol..nmol.L.,
    dhea = DHEA..nmol.L.,
    date = Collection.Date)
```

# check that everyone has 12 records
```{r}
data %>%
  count(id) %>% count(n)
# Yes
```
```{r}
data %>%
  group_by(id, day, sample) %>%
  filter(n() > 1) %>%
  arrange(id, day, sample) %>%
  ungroup()
# 3029 has wrong day number
```
```{r}
# since this is a small dataset, we change the day number of 3029 manually
data <- data %>%
  mutate(
    day = if_else(
      id == 3029,
      case_when(
        date == "10/7/2018"  ~ 1,
        date == "10/10/2018" ~ 2,
        TRUE ~ day),
      day))
```



# check if the first sample always has wake-up time
```{r}
table(
  sample1 = data$sample == 1,
  wake_na = data$sleep != "")
# Yes, sample = 1 means having wake-up time
```
# check missing rows
```{r}
n_total <- nrow(data)

var_missing <- data.frame(
  var = c("booklet", "cap", "cortisol", "dhea"),
  missing = c(
    sum(is.na(data$booklet)),
    sum(is.na(data$cap)),
    sum(is.na(data$cortisol)),
    sum(is.na(data$dhea))
  )
) %>%
  mutate(percent = round(missing / n_total * 100, 1))

q1 <- data.frame(
  var = "Q1 sample",
  missing = sum(is.na(data$booklet) | is.na(data$cap)),
  percent = round(sum(is.na(data$booklet) | is.na(data$cap)) / n_total * 100, 1)
)

# we know that we will need to get rid of outlier later
q3_cort_out <- data %>%
  mutate(
    cortisol_cleaned = if_else(cortisol > 80, NA_real_, cortisol)
  ) %>%
  summarise(
    var = "Q3 sample (cort)",
    missing = sum(is.na(booklet) | is.na(cortisol_cleaned)),
    percent = round(sum(is.na(booklet) | is.na(cortisol_cleaned)) / n_total * 100, 1))

# Q3 sample for dhea: remove outlier and set 3037 to missing
q3_dhea_out <- data %>%
  mutate(
    dhea_cleaned = if_else(dhea >= 5.205 | id == 3037, NA_real_, dhea)
  ) %>%
  summarise(
    var = "Q3 sample (dhea)",
    missing = sum(is.na(booklet) | is.na(dhea_cleaned)),
    percent = round(sum(is.na(booklet) | is.na(dhea_cleaned)) / n_total * 100, 1)
  )

missing_table <- bind_rows(var_missing, q1, q3_cort_out, q3_dhea_out)
missing_table
```
# check booklet missing included in cap missing
```{r}
table(
  booklet_na = is.na(data$booklet),
  cap_na = is.na(data$cap))
# No, there are only 17 rows overlapping
# we only have 268/372 rows in terms of non-missing time
```

# check range of time and outcomes
```{r}
# plot histograms
ggplot(data, aes(x = booklet)) +
  geom_histogram(bins = 30, na.rm = TRUE) +
  labs(title = "Histogram of booklet")

ggplot(data, aes(x = cap)) +
  geom_histogram(bins = 30, na.rm = TRUE) +
  labs(title = "Histogram of cap")

ggplot(data, aes(x = cortisol)) +
  geom_histogram(bins = 30, na.rm = TRUE) +
  labs(title = "Histogram of cortisol")

ggplot(data, aes(x = dhea)) +
  geom_histogram(bins = 30, na.rm = TRUE) +
  labs(title = "Histogram of dhea")
```

```{r}
data %>%
  summarise(
    booklet_min = min(booklet, na.rm = TRUE),
    booklet_max = max(booklet, na.rm = TRUE),
    cap_min = min(cap, na.rm = TRUE),
    cap_max = max(cap, na.rm = TRUE),
    cortisol_min = min(cortisol, na.rm = TRUE),
    cortisol_max = max(cortisol, na.rm = TRUE),
    dhea_min = min(dhea, na.rm = TRUE),
    dhea_max = max(dhea, na.rm = TRUE))
```
```{r}
# following advice from PI, set threshold for two outcomes and remove outliers
data <- data %>%
  mutate(
    dhea_cleaned = if_else(dhea >= 5.205, NA_real_, dhea),
    cortisol_cleaned = if_else(cortisol > 80, NA_real_, cortisol))
# do we believe in it?
```

# Question 1: consistency of booklet and cap
```{r}
# draw the scatter plot of both time with linear regression trend line
ggplot(data %>% filter(!is.na(cap), !is.na(booklet)),
       aes(x = cap, y = booklet)) +
  geom_point(alpha = 0.4) +
  geom_smooth(method = "lm", se = FALSE) +
  labs(
    x = "Electronic cap time (min since waking)",
    y = "Booklet-recorded time (min since waking)") +
  theme_minimal()
```

```{r}
# correlation: pearson and spearman
cor(data$cap, data$booklet, use = "complete.obs")
cor(data$cap, data$booklet, use = "complete.obs",method = "spearman")
```
```{r}
fit_time <- lmer(
  booklet ~ cap + (1 | id),
  data = data,
  REML = FALSE)

summary(fit_time)
confint(fit_time)
```

```{r}
# Bland–Altman: every point represents a pair of measurement
data_ba <- data %>%
  filter(!is.na(booklet), !is.na(cap)) %>%
  mutate(
    mean_time = (booklet + cap) / 2, # time of the pair of measurement
    diff_time = booklet - cap) # measurement difference

mean_diff <- mean(data_ba$diff_time)
sd_diff <- sd(data_ba$diff_time) # for constructing the CI
upper <- mean_diff + 1.96 * sd_diff
lower <- mean_diff - 1.96 * sd_diff

ggplot(data_ba, aes(x = mean_time, y = diff_time)) +
  geom_point(alpha = 0.4) +
  geom_hline(yintercept = mean_diff, linetype = "solid") +
  geom_hline(yintercept = upper, linetype = "dashed") +
  geom_hline(yintercept = lower, linetype = "dashed") +
  annotate("text", x = Inf, y = mean_diff,
           label = round(mean_diff, 2), hjust = 1.1, color = "red") +
  annotate("text", x = Inf, y = upper, 
           label = round(upper, 2), hjust = 1.1, color = "red") +
  annotate("text", x = Inf, y = lower, 
           label = round(lower, 2), hjust = 1.1, color = "red") +
  labs(x = "Mean time of measurement",
       y = "Time difference: Booklet – cap (min)") +
  theme_minimal()
```

# Question 2: adherence at 30min and 10h
```{r}
data_q2 <- data %>%
  mutate(
    target_time = case_when(
      sample == 2 ~ 30,
      sample == 4 ~ 600,),
    # here we are only interested in adherence of booklet time
    time_error = if_else(!is.na(booklet) & !is.na(target_time),
                         booklet - target_time,
                         NA_real_),
    abs_error = abs(time_error),
    compliance = case_when(
      is.na(target_time) ~ NA_character_,
      is.na(booklet) ~ NA_character_,
      abs_error <= 7.5 ~ "Good",
      abs_error <= 15 ~ "Adequate",
      TRUE ~ "Poor"))

data_q2 %>%
  filter(sample %in% c(2, 4)) %>%
  mutate(compliance = if_else(is.na(compliance), 
                              "Missing", compliance),
         compliance = factor(compliance, 
          levels = c("Good", "Adequate", "Poor", "Missing"))) %>%
  count(sample, compliance, .drop = TRUE) %>%
  group_by(sample) %>%
  mutate(percent = round(n / sum(n) * 100, 2))
```

# Question 3: change of outcome over time
```{r}
# given that both dhea and cortisol are very right skewed (see above) we have to do log-transform
# have checked before that both outcomes don't have zero
# use cleaned version
data <- data %>%
  mutate(log_cort = log(cortisol_cleaned), log_dhea = log(dhea_cleaned))

ggplot(data, aes(x = log_cort)) +
  geom_histogram(bins = 30, na.rm = TRUE) +
  labs(title = "Histogram of log cortisol")

ggplot(data, aes(x = log_dhea)) +
  geom_histogram(bins = 30, na.rm = TRUE) +
  labs(title = "Histogram of log dhea")
# Now both look much more linearly distributed
```



```{r}
data_q3 <- data %>%
  mutate(
    t1_30 = if_else(booklet <= 30, cap, 30),
    t2_30 = if_else(booklet > 30, cap - 30, 0))

# exclude 3037 from dhea analysis as it has too many outliers
data_q3_dhea <- data_q3 %>%
  filter(id != 3037)


ggplot(data, aes(x = log(booklet + 1), y = log_cort, group = id)) +
  geom_line(alpha = 0.3, color = "grey50") +
  geom_smooth(aes(group = 1), method = "gam", formula = y ~ s(x, bs="cs"), se = TRUE, color="blue") +
  scale_x_continuous(
    breaks = log(c(0,5,10,15,30,60,120,240,600)+1),
    labels = c(0,5,10,15,30,60,120,240,600)
  ) +
  labs(
    x = "Minutes since waking (log scale for display)",
    y = "Log cortisol"
  ) +
  theme_minimal()
```

```{r}
ggplot(data_q3_dhea, aes(x = log(booklet + 1), y = log_dhea, group = id)) +
  geom_line(alpha = 0.3, color = "grey50") +
  geom_smooth(aes(group = 1), method = "gam", formula = y ~ s(x, bs="cs"), se = TRUE, color="blue") +
  scale_x_continuous(
    breaks = log(c(0,5,10,15,30,60,120,240,600)+1),
    labels = c(0,5,10,15,30,60,120,240,600)
  ) +
  labs(
    x = "Minutes since waking (log scale for display)",
    y = "Log DHEA"
  ) +
  theme_minimal()
```


```{r}
# Cortisol
cort_fit_30 <- lmer(log_cort ~ t1_30 + t2_30 + (1 | id), data = data_q3)
summary(cort_fit_30)

# DHEA
dhea_fit_30 <- lmer(log_dhea ~ t1_30 + t2_30 + (1 | id), data = data_q3_dhea)
summary(dhea_fit_30)
```



