---
title: "Project1"
author: "Guangyu Qiu"
date: "2026-01-26"
output: pdf_document
---
# general setting
```{r}
library(tidyverse)
library(lme4)
library(lmerTest)
library(mgcv)
library(broom.mixed)
library(knitr)
library(kableExtra)
library(patchwork)
library(here)
library(naniar)
library(janitor)
library(skimr)
library(gtsummary)
library(cmdstanr)
library(bayesplot)
library(posterior) # trace plot
library(loo)
```



```{r}
# data import, rename and recode some variables
data <- read.csv(here("Project_1","Data", "hiv_6624_final.csv")) %>% clean_names() %>%
  filter(years %in% c(0,2)) %>%
  group_by(newid) %>%
  filter(all(c(0,2) %in% years)) %>%
  ungroup() %>%
  transmute(
    years,
    id = newid,
    drugs = ifelse(hard_drugs == 0, "No", "Yes"),
    vload,
    log10_vload = log10(vload),
    leu3n = ifelse(leu3n < 0, NA_real_, leu3n),
    phys = agg_phys,
    ment = agg_ment,
    age,
    race = case_when(
      race == 1 ~ "Non-Hispanic White",
      race %in% c(2,3,4,5,6,7,8) ~ "Other",
      TRUE ~ NA_character_
    ),
    edu = case_when(
      educbas %in% c(1,2,3,4) ~ "No college degree or lower",
      educbas %in% c(5,6,7) ~ "College or higher",
      TRUE ~ NA_character_
    ),
    bmi = case_when(
      bmi == -1 | bmi > 100 ~ NA_character_,
      bmi < 18.5 ~ "Underweight",
      bmi >= 18.5 & bmi <= 24.9 ~ "Normal",
      bmi > 24.9 ~ "Overweight",
      TRUE ~ NA_character_
    ),
    adherence = case_when(
      adh == 1 ~ "100%",
      adh == 2 ~ "95-99%",
      adh == 3 ~ "75-94%",
      adh == 4 ~ "<75%",
      TRUE ~ NA_character_
    ),
    smoke = case_when(
      smoke %in% c(1,2) ~ "Non-current",
      smoke == 3 ~ "Current smoker",
      TRUE ~ NA_character_
    ),
  )

#  pivot wider
data_wide <- data %>%
  pivot_wider(
    id_cols = id,
    names_from = years,
    values_from = c(log10_vload, leu3n, phys, ment,
                    drugs, age, race, edu,
                    bmi, adherence, smoke))
# outcome we use
data_wide <- data_wide %>%
  mutate(
    log10_vload_change = log10_vload_2 - log10_vload_0,
    leu3n_change = leu3n_2 - leu3n_0,
    phys_change = phys_2 - phys_0,
    ment_change = ment_2 - ment_0)

```



# missingness check
```{r}
outcomes <- c("log10_vload_change","leu3n_change","phys_change","ment_change")
predictors <- c("drugs_0","age_0","race_0","edu_0","bmi_0",
                "adherence_2","smoke_0")

vars <- c(outcomes, predictors)

missing_summary <- data_wide %>%
  summarise(
    across(
      all_of(vars),
      list(
        missing_n   = ~ sum(is.na(.)),
        missing_pct = ~ mean(is.na(.))
      )
    )
  ) %>%
  pivot_longer(
    everything(),
    names_to = c("variable", ".value"),
    names_sep = "_missing_"
  )

print(missing_summary)
```

```{r}
# sample size check
all_vars <- c(outcomes, predictors)
n_complete_all <- sum(complete.cases(data_wide[, all_vars]))
n_complete_all
```

```{r}
# This is the final dataset we use
data_final <- data_wide %>%
  filter(complete.cases(across(all_vars)))
```



# range check
```{r}
range_check <- data_final %>%
  summarise(across(c(log10_vload_0, log10_vload_2, leu3n_0, leu3n_2,phys_0, phys_2, ment_0, ment_2,log10_vload_change, leu3n_change,phys_change, ment_change, age_0),
                   list(min = ~min(., na.rm = TRUE),
                        max = ~max(., na.rm = TRUE)))) %>%
  pivot_longer(
    cols = everything(),
    names_to = "variable_stat",
    values_to = "value"
  ) %>%
  mutate(
    stat = ifelse(grepl("_min$", variable_stat), "min", "max"),
    variable = sub("_(min|max)$", "", variable_stat)
  ) %>%
  select(variable, stat, value) %>%
  pivot_wider(
    names_from = stat,
    values_from = value
  )

print(range_check)
```

```{r}
outcomes <- c("log10_vload_change","leu3n_change","phys_change","ment_change")
outcome_labels <- c(
  "log10_vload_change" = "log10(Viral Load) Change",
  "leu3n_change" = "CD4+ T Cell Count Change",
  "phys_change" = "Aggregate Physical QoL Score Change",
  "ment_change" = "Aggregate Mental QoL Score Change"
)

plots <- lapply(outcomes, function(var){
  ggplot(data_final, aes_string(x = var)) +
    geom_histogram(bins = 30, fill = "#2c7fb8", color = "black", alpha = 0.7) +
    theme_minimal() +
    labs(title = outcome_labels[var], x = "Change (2y - baseline)", y = "Count")
})

combined_plot <- (plots[[1]] | plots[[2]]) / (plots[[3]] | plots[[4]])

print(combined_plot)
ggsave(filename = here("Project_1","Report","outcome_hist_2x2.png"),
       plot = combined_plot, width = 10, height = 8)
```

# Table 1
```{r}
var_labels <- list(
  age_0 = "Age (years)",
  race_0 = "Race/Ethnicity",
  edu_0 = "Education",
  bmi_0 = "BMI category",
  smoke_0 = "Smoking",
  adherence_2 = "Adherence to Treatment at Year 2",
  log10_vload_change = "Change in log10 Viral Load",
  leu3n_change = "Change in CD4 count",
  phys_change = "Change in Physical Health",
  ment_change = "Change in Mental Health"
)

table1 <- data_final %>%
  select(drugs_0, age_0, race_0, edu_0, bmi_0,
         smoke_0, adherence_2,
         log10_vload_change, leu3n_change, phys_change, ment_change) %>%
  tbl_summary(
    by = drugs_0,
    label = var_labels,
    missing = "ifany",
    statistic = list(
      all_continuous() ~ "{mean} ({sd})",
      all_categorical() ~ "{n} ({p}%)"
    ),
    digits = list(
      all_continuous() ~ 2),
    type = list(
      age_0 ~ "continuous",
      log10_vload_change ~ "continuous",
      leu3n_change ~ "continuous",
      phys_change ~ "continuous",
      ment_change ~ "continuous"
    )
  ) %>%
    add_p(
    test = list(
      all_continuous() ~ "t.test",
      all_categorical() ~ "chisq.test"
    )
  ) %>%
  #add_overall(last = TRUE) %>%
  bold_labels()

table1
```

# Correlation
```{r}
vars_corr <- data_final %>%
  dplyr::select(
    drugs_0,
    log10_vload_change,
    leu3n_change,
    phys_change,
    ment_change,
    age_0,
    race_0,
    edu_0,
    bmi_0,
    adherence_2,
    smoke_0
  ) %>%
  dplyr::mutate(
    drugs_0 = as.numeric(drugs_0 == "Yes"),
    race_0 = as.numeric(race_0 == "Other"),
    edu_0 = as.numeric(edu_0 == "College or higher"),
    bmi_0 = as.numeric(bmi_0 == "Overweight"),
    adherence_2 = as.numeric(adherence_2 %in% c("100%", "95-99%")),
    smoke_0 = as.numeric(smoke_0 == "Current smoker")
  )

cor_mat <- cor(
  vars_corr,
  use = "pairwise.complete.obs"
)

cor_df <- as.data.frame(round(cor_mat, 2))

cor_long <- cor_df %>%
  tibble::rownames_to_column("Var1") %>%
  pivot_longer(
    -Var1,
    names_to = "Var2",
    values_to = "Correlation"
  )

var_labels_corr <- c(
  log10_vload_change = "log10 Viral Load change",
  leu3n_change = "CD4 change",
  phys_change = "Physical Health change",
  ment_change = "Mental Health change",
  age_0 = "Age",
  drugs_0 = "Drug Use",
  race_0 = "Race:Other",
  edu_0 = "Education:College+",
  bmi_0 = "BMI:Overweight",
  adherence_2 = "Adherence High",
  smoke_0 = "Current Smoker"
)

var_order <- colnames(vars_corr)

cor_long <- cor_long %>%
  mutate(
    Var1 = factor(Var1, levels = var_order),
    Var2 = factor(Var2, levels = var_order)
  )

ggplot(cor_long, aes(x = Var2, y = Var1, fill = Correlation)) +
  geom_tile(color = "white") +
  geom_text(aes(label = Correlation), size = 4) +
  scale_fill_gradient2(
    low = "blue",
    mid = "white",
    high = "red",
    midpoint = 0,
    limits = c(-1, 1)
  ) +
  scale_x_discrete(labels = var_labels_corr) +
  scale_y_discrete(labels = var_labels_corr) +
  ggtitle("Pearson Correlation Matrix") +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, size = 12),
    axis.text.y = element_text(size = 12),
    axis.title = element_blank(),
    plot.title = element_text(size = 18, face = "bold", hjust = 0.5)
  )

ggsave(
  "correlation_matrix.png",
  plot = last_plot(),
  width = 10, height = 9, dpi = 300,
  bg = "white")
```

# boxplot
```{r}
data_long_outcome <- data_final %>%
  select(drugs_0,
         log10_vload_change,
         leu3n_change,
         phys_change,
         ment_change) %>%
  pivot_longer(
    cols = -drugs_0,
    names_to = "Outcome",
    values_to = "Value"
  )
outcome_labels <- c(
  log10_vload_change = "Change in log10 Viral Load",
  leu3n_change = "Change in CD4 count",
  phys_change = "Change in Physical Health",
  ment_change = "Change in Mental Health"
)
ggplot(data_long_outcome,
       aes(x = drugs_0, y = Value)) +
  geom_boxplot(fill = "lightblue", alpha = 0.7) +
  facet_wrap(~Outcome,
             scales = "free",
             labeller = labeller(Outcome = outcome_labels)) +
  labs(
    x = "Drug Use at Baseline",
    y = "Change from Baseline to Year 2",
    title = "Change in Outcomes by Drug Use"
  ) +
  theme_minimal() +
  theme(
    strip.text = element_text(size = 15, face = "bold"),
    strip.background = element_rect(fill = "grey90", color = "black"),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14),
    plot.title = element_text(size = 18, face = "bold", hjust = 0.5)
  )

ggsave("boxplot.png", plot = last_plot(), width = 12, height = 10, dpi = 300)
```


# Stan data and model
```{r}
data_final <- data_final %>%
  mutate(
    drugs = ifelse(drugs_0 == "Yes", 1, 0),
    race = ifelse(race_0 == "Other", 1, 0),
    edu = ifelse(edu_0 == "College or higher", 1, 0),
    bmi_overweight  = ifelse(bmi_0 == "Overweight", 1, 0),
    bmi_underweight = ifelse(bmi_0 == "Underweight", 1, 0),
    adherence_95   = ifelse(adherence_2 == "95-99%", 1, 0),
    adherence_75   = ifelse(adherence_2 == "75-94%", 1, 0),
    adherence_less = ifelse(adherence_2 == "<75%", 1, 0),
    smoke = ifelse(smoke_0 == "Current smoker", 1, 0))

linear_model <- cmdstan_model(here("Project_1","Code","stan","linear.stan"))

linear_adh_model <- cmdstan_model(here("Project_1","Code","stan","linear_adh.stan"))



stan_data_vload_adh <- list(
  N = nrow(data_final),
  y = data_final$log10_vload_change,
  drugs_0 = data_final$drugs,
  age_0 = data_final$age_0,
  race_0 = data_final$race,
  edu_0 = data_final$edu,
  bmi_overweight  = data_final$bmi_overweight,
  bmi_underweight = data_final$bmi_underweight,
  adherence_95   = data_final$adherence_95,
  adherence_75   = data_final$adherence_75,
  adherence_less = data_final$adherence_less,
  smoke_0 = data_final$smoke
)

stan_data_vload <- list(
  N = nrow(data_final),
  y = data_final$log10_vload_change,
  drugs_0 = data_final$drugs,
  age_0 = data_final$age_0,
  race_0 = data_final$race,
  edu_0 = data_final$edu,
  bmi_overweight  = data_final$bmi_overweight,
  bmi_underweight = data_final$bmi_underweight,
  smoke_0 = data_final$smoke
)

stan_data_leu3n_adh <- list(
  N = nrow(data_final),
  y = data_final$leu3n_change,
  drugs_0 = data_final$drugs,
  age_0 = data_final$age_0,
  race_0 = data_final$race,
  edu_0 = data_final$edu,
  bmi_overweight  = data_final$bmi_overweight,
  bmi_underweight = data_final$bmi_underweight,
  adherence_95   = data_final$adherence_95,
  adherence_75   = data_final$adherence_75,
  adherence_less = data_final$adherence_less,
  smoke_0 = data_final$smoke
)

stan_data_leu3n <- list(
  N = nrow(data_final),
  y = data_final$leu3n_change,
  drugs_0 = data_final$drugs,
  age_0 = data_final$age_0,
  race_0 = data_final$race,
  edu_0 = data_final$edu,
  bmi_overweight  = data_final$bmi_overweight,
  bmi_underweight = data_final$bmi_underweight,
  smoke_0 = data_final$smoke
)

stan_data_phys_adh <- list(
  N = nrow(data_final),
  y = data_final$phys_change,
  drugs_0 = data_final$drugs,
  age_0 = data_final$age_0,
  race_0 = data_final$race,
  edu_0 = data_final$edu,
  bmi_overweight  = data_final$bmi_overweight,
  bmi_underweight = data_final$bmi_underweight,
  adherence_95   = data_final$adherence_95,
  adherence_75   = data_final$adherence_75,
  adherence_less = data_final$adherence_less,
  smoke_0 = data_final$smoke
)

stan_data_phys <- list(
  N = nrow(data_final),
  y = data_final$phys_change,
  drugs_0 = data_final$drugs,
  age_0 = data_final$age_0,
  race_0 = data_final$race,
  edu_0 = data_final$edu,
  bmi_overweight  = data_final$bmi_overweight,
  bmi_underweight = data_final$bmi_underweight,
  smoke_0 = data_final$smoke
)

stan_data_ment_adh <- list(
  N = nrow(data_final),
  y = data_final$ment_change,
  drugs_0 = data_final$drugs,
  age_0 = data_final$age_0,
  race_0 = data_final$race,
  edu_0 = data_final$edu,
  bmi_overweight  = data_final$bmi_overweight,
  bmi_underweight = data_final$bmi_underweight,
  adherence_95   = data_final$adherence_95,
  adherence_75   = data_final$adherence_75,
  adherence_less = data_final$adherence_less,
  smoke_0 = data_final$smoke
)

stan_data_ment <- list(
  N = nrow(data_final),
  y = data_final$ment_change,
  drugs_0 = data_final$drugs,
  age_0 = data_final$age_0,
  race_0 = data_final$race,
  edu_0 = data_final$edu,
  bmi_overweight  = data_final$bmi_overweight,
  bmi_underweight = data_final$bmi_underweight,
  smoke_0 = data_final$smoke
)
```

# Stan model template
```{r}
# These are the data for all 8 models
# stan_data_vload_adh
# stan_data_vload
# stan_data_leu3n_adh
# stan_data_leu3n
# stan_data_phys_adh
# stan_data_phys
# stan_data_ment_adh
# stan_data_ment

# These are the two stan:
# linear_adh_model
# linear_model

fit_stan_adh <- linear_adh_model$sample(
  data = stan_data_vload_adh,
  seed = 648,
  chains = 4,
  iter_warmup = 2000,
  iter_sampling = 10000,
  parallel_chains = 4
)

fit_stan_adh$summary()
```

```{r}
posterior_matrix <- fit_stan_adh$draws(format = "matrix")
posterior_matrix_params <- posterior_matrix[, !colnames(posterior_matrix) %in% "lp__"]
mcmc_intervals(posterior_matrix_params, prob = 0.95)
```
```{r}
posterior <- as_draws_array(fit_stan_adh$draws())
mcmc_trace(posterior, pars = c("beta_drugs_0"))
```

# virus load
```{r}
fit_stan_vload_adh <- linear_adh_model$sample(
  data = stan_data_vload_adh,
  seed = 648,
  chains = 4,
  iter_warmup = 2000,
  iter_sampling = 10000,
  parallel_chains = 4
)

fit_stan_vload_adh$summary()
```

```{r}
fit_stan_vload <- linear_model$sample(
  data = stan_data_vload,
  seed = 648,
  chains = 4,
  iter_warmup = 2000,
  iter_sampling = 10000,
  parallel_chains = 4
)

fit_stan_vload$summary()
```
```{r}
log_lik_vload_adh <- fit_stan_vload_adh$draws("log_lik", format = "matrix")
log_lik_vload <- fit_stan_vload$draws("log_lik", format = "matrix")
waic(log_lik_vload_adh)
waic(log_lik_vload)
```
```{r}
posterior <- as_draws_array(fit_stan_vload$draws())
mcmc_trace(posterior, pars = c("beta_drugs_0"))
```


```{r}
vload_adh_fit <- lm(
  log10_vload_change ~
    drugs_0 + age_0 + race_0 + edu_0 + bmi_0 +
    adherence_2 + smoke_0,
  data = data_final
)

summary(vload_adh_fit)
```

```{r}
vload_fit <- lm(
  log10_vload_change ~
    drugs_0 + age_0 + race_0 + edu_0 + bmi_0 + smoke_0,
  data = data_final
)

summary(vload_fit)
```
# T cell count
```{r}
fit_stan_leu3n_adh <- linear_adh_model$sample(
  data = stan_data_leu3n_adh,
  seed = 648,
  chains = 4,
  iter_warmup = 2000,
  iter_sampling = 10000,
  parallel_chains = 4
)

fit_stan_leu3n_adh$summary()
```

```{r}
fit_stan_leu3n <- linear_model$sample(
  data = stan_data_leu3n,
  seed = 648,
  chains = 4,
  iter_warmup = 2000,
  iter_sampling = 10000,
  parallel_chains = 4
)

fit_stan_leu3n$summary()
```

```{r}
posterior <- as_draws_array(fit_stan_leu3n$draws())
mcmc_trace(posterior, pars = c("beta_drugs_0"))
```

```{r}
leu3n_adh_fit <- lm(
  leu3n_change ~
    drugs_0 + age_0 + race_0 + edu_0 + bmi_0 +
    adherence_2 + smoke_0,
  data = data_final
)

summary(leu3n_adh_fit)
```

```{r}
leu3n_fit <- lm(
  leu3n_change ~
    drugs_0 + age_0 + race_0 + edu_0 + bmi_0 + smoke_0,
  data = data_final
)

summary(leu3n_fit)
```
```{r}
log_lik_leu3n_adh <- fit_stan_leu3n_adh$draws("log_lik", format = "matrix")
log_lik_leu3n <- fit_stan_leu3n$draws("log_lik", format = "matrix")
waic(log_lik_leu3n_adh)
waic(log_lik_leu3n)
```
# physical score
```{r}
fit_stan_phys_adh <- linear_adh_model$sample(
  data = stan_data_phys_adh,
  seed = 648,
  chains = 4,
  iter_warmup = 2000,
  iter_sampling = 10000,
  parallel_chains = 4
)

fit_stan_phys_adh$summary()
```

```{r}
fit_stan_phys <- linear_model$sample(
  data = stan_data_phys,
  seed = 648,
  chains = 4,
  iter_warmup = 2000,
  iter_sampling = 10000,
  parallel_chains = 4
)

fit_stan_phys$summary()
```

```{r}
posterior <- as_draws_array(fit_stan_phys$draws())
mcmc_trace(posterior, pars = c("beta_drugs_0"))
```

```{r}
log_lik_phys_adh <- fit_stan_phys_adh$draws("log_lik", format = "matrix")
log_lik_phys <- fit_stan_phys$draws("log_lik", format = "matrix")
waic(log_lik_phys_adh)
waic(log_lik_phys)
```

```{r}
phys_adh_fit <- lm(
  phys_change ~
    drugs_0 + age_0 + race_0 + edu_0 + bmi_0 +
    adherence_2 + smoke_0,
  data = data_final
)

summary(phys_adh_fit)
```

```{r}
phys_fit <- lm(
  phys_change ~
    drugs_0 + age_0 + race_0 + edu_0 + bmi_0 + smoke_0,
  data = data_final
)

summary(phys_fit)
```

# mental score
```{r}
fit_stan_ment_adh <- linear_adh_model$sample(
  data = stan_data_ment_adh,
  seed = 648,
  chains = 4,
  iter_warmup = 2000,
  iter_sampling = 10000,
  parallel_chains = 4
)

fit_stan_ment_adh$summary()
```

```{r}
fit_stan_ment <- linear_model$sample(
  data = stan_data_ment,
  seed = 648,
  chains = 4,
  iter_warmup = 2000,
  iter_sampling = 10000,
  parallel_chains = 4
)

fit_stan_ment$summary()
```

```{r}
log_lik_ment_adh <- fit_stan_ment_adh$draws("log_lik", format = "matrix")
log_lik_ment <- fit_stan_ment$draws("log_lik", format = "matrix")
waic(log_lik_ment_adh)
waic(log_lik_ment)
```

```{r}
posterior <- as_draws_array(fit_stan_ment_adh$draws())
mcmc_trace(posterior, pars = c("beta_drugs_0"))
```

```{r}
ment_adh_fit <- lm(
  ment_change ~
    drugs_0 + age_0 + race_0 + edu_0 + bmi_0 +
    adherence_2 + smoke_0,
  data = data_final
)

summary(ment_adh_fit)
```
```{r}
ment_fit <- lm(
  ment_change ~
    drugs_0 + age_0 + race_0 + edu_0 + bmi_0 + smoke_0,
  data = data_final
)

summary(ment_fit)
```



# density plot
```{r}
extract_density <- function(fit, outcome_name) {
  draws <- as_draws_matrix(fit$draws("beta_drugs_0"))
  
  tibble(
    value = as.numeric(draws),
    Outcome = outcome_name
  )
}

density_df <- bind_rows(
  extract_density(fit_stan_vload, "Viral Load"),
  extract_density(fit_stan_leu3n, "CD4"),
  extract_density(fit_stan_phys, "Physical Health"),
  extract_density(fit_stan_ment, "Mental Health")
)

ggplot(density_df,
       aes(x = value)) +
  geom_density(fill = "lightblue", alpha = 0.6) +
  geom_vline(xintercept = 0,
             linetype = "dashed",
             color = "red") +
  facet_wrap(~Outcome,
             scales = "free",
             ncol = 2) +
  labs(
    x = "Posterior Drug Effect",
    y = "Density",
    title = "Posterior Distribution of Drug Effect Across Outcomes"
  ) +
  theme_minimal() +
  theme(
    strip.text = element_text(size = 14, face = "bold"),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14),
    plot.title = element_text(size = 18, face = "bold", hjust = 0.5)
  )

ggsave(
  "posterior_density_drug_effect.png",
  plot = last_plot(),
  width = 12,
  height = 10,
  dpi = 600,
  bg = "white"
)
```
# posterior P value
```{r}
posterior_p_clinical <- function(fit, model_name, outcome) {
  
  draws <- as_draws_matrix(fit$draws("beta_drugs_0"))
  draws <- as.numeric(draws)

  cutoff <- case_when(
    outcome == "log10_vload_change" ~ 0.5,
    outcome == "leu3n_change" ~ -50,
    outcome == "phys_change" ~ -2,
    outcome == "ment_change" ~ -2
  )

  post_prob <- case_when(
    outcome == "log10_vload_change" ~ mean(draws < cutoff),
    TRUE ~ mean(draws > cutoff))
  
  est <- mean(draws)
  lower <- quantile(draws, 0.025)
  upper <- quantile(draws, 0.975)

  est_fmt <- dplyr::case_when(
    outcome == "log10_vload_change" ~ sprintf("%.3f", est),
    outcome == "leu3n_change" ~ sprintf("%.1f", est),
    outcome %in% c("phys_change", "ment_change") ~ sprintf("%.2f", est)
  )
  
  ci_fmt <- dplyr::case_when(
    outcome == "log10_vload_change" ~ sprintf("(%.3f, %.3f)", lower, upper),
    outcome == "leu3n_change" ~ sprintf("(%.1f, %.1f)", lower, upper),
    outcome %in% c("phys_change", "ment_change") ~ sprintf("(%.2f, %.2f)", lower, upper)
  )

  tibble(
    Model = model_name,
    Outcome = outcome,
    Estimate_CI = paste0(est_fmt, " ", ci_fmt),
    Post_Prob_ClinicallyMeaningful = sprintf("%.3f", post_prob)
  )
}

posterior_results <- bind_rows(
  posterior_p_clinical(fit_stan_vload, "Viral Load", "log10_vload_change"),
  posterior_p_clinical(fit_stan_leu3n, "CD4", "leu3n_change"),
  posterior_p_clinical(fit_stan_phys, "Physical Health", "phys_change"),
  posterior_p_clinical(fit_stan_ment, "Mental Health", "ment_change"),
  posterior_p_clinical(fit_stan_vload_adh, "Viral Load + Adherence", "log10_vload_change"),
  posterior_p_clinical(fit_stan_leu3n_adh, "CD4 + Adherence", "leu3n_change"),
  posterior_p_clinical(fit_stan_phys_adh, "Physical Health + Adherence", "phys_change"),
  posterior_p_clinical(fit_stan_ment_adh, "Mental Health + Adherence", "ment_change")
)


posterior_results
```

