---
title: "Project2"
author: "Guangyu Qiu"
date: "2026-03-23"
output: pdf_document
---
```{r}
library(readr)
library(powertools)
library(tidyverse)
```

```{r}
data <- read_csv("PrelimData.csv")
data
```

```{r}
# quick check
cor_mat <- cor(data, use = "pairwise.complete.obs", method = "pearson")
print(cor_mat)
```
```{r}
cor_mat <- cor(data, use = "pairwise.complete.obs", method = "pearson")

# pivot to long format
cor_long <- as.data.frame(round(cor_mat, 2)) %>%
  tibble::rownames_to_column("Var1") %>%
  pivot_longer(-Var1, names_to = "Var2", values_to = "Correlation")

# label
var_labels <- c(
  CVLT_CNG3 = "CVLT (Cognitive)",
  CORT_CNG3 = "CORT (Cognitive)",
  IL_6 = "IL-6 (Inflammation)",
  MCP_1 = "MCP-1 (Inflammation)"
)

var_order <- colnames(data)

cor_long <- cor_long %>%
  mutate(
    Var1 = factor(Var1, levels = var_order),
    Var2 = factor(Var2, levels = var_order)
  )

p <- ggplot(cor_long, aes(x = Var2, y = Var1, fill = Correlation)) +
  geom_tile(color = "white") +
  geom_text(aes(label = Correlation), size = 6) +
  scale_fill_gradient2(
    low = "blue",
    mid = "white",
    high = "red",
    midpoint = 0,
    limits = c(-1, 1)
  ) +
  scale_x_discrete(labels = var_labels) +
  scale_y_discrete(labels = var_labels) +
  ggtitle("Pearson Correlation Matrix") + 
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, size = 14),
    axis.text.y = element_text(size = 14),
    axis.title = element_blank(),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white")
  )

print(p)

ggsave(
  "correlation_matrix_4vars.png",
  plot = p,
  width = 6, height = 5, dpi = 300,
  bg = "white"
)
```


```{r}
# given sample size, what's our power
n_total <- 192
dropout <- 0.10 # assume by PI
n_eff <- floor(n_total * (1 - dropout))

alpha <- 0.05/6 # use Bonferroni to adjust for type one error rate
power_target <- 0.8 # target power
predictor_set <- 3:8 # we don't know how many covariates will be added, so we set this range
r_range <- seq(0.1, 0.7, by = 0.1) # partial correlation range

results <- sapply(predictor_set, function(k) {
  sapply(r_range, function(r) {
    mlrF.partial(N = n_eff, p = k, q = 1, pc = r, alpha = alpha, power = NULL)
  })
})

power_df <- as.data.frame(results)
colnames(power_df) <- paste0("k=", predictor_set)
rownames(power_df) <- paste0("r=", r_range)

power_df
```

```{r}
# calculate sample size need to reach 80% power
alpha <- 0.05/6 # use Bonferroni to adjust for type one error rate
power_target <- 0.8 # target power
predictor_set <- 3:8  # we don't know how many covariates will be added, so we set this range
r_range <- seq(0.1, 0.7, by = 0.1)  # partial correlation range
q <- 1     # we only test the first predictor

results <- sapply(predictor_set, function(k) {
  sapply(r_range, function(r) {
    mlrF.partial(
      N = NULL,  
      p = k,
      q = q,
      pc = r,
      alpha = alpha,
      power = power_target
    )
  })
})

sample_df <- as.data.frame(results)
colnames(sample_df) <- paste0("k=", predictor_set)
rownames(sample_df) <- paste0("r=", r_range)

sample_df
```
```{r}
# plotting: power vs correlation
n_total <- 192
dropout <- 0.10
n_eff <- floor(n_total * (1 - dropout))  # 172
alpha <- 0.05/6   # Bonferroni
q <- 1
k <- 8  # set to 8
r_range <- seq(0.1, 0.7, by = 0.01) # compute power every 0.01 correlation

power_values <- sapply(r_range, function(r) {
  mlrF.partial(N = n_eff, p = k, q = q, pc = r, alpha = alpha, power = NULL)
})

power_df <- data.frame(
  r = r_range,
  power = power_values
)

# correlation at power = 0.8
r_80 <- min(r_range[power_values >= 0.8])

p_power <- ggplot(power_df, aes(x = r, y = power)) +
  geom_line(size = 1, color = "blue") +
  geom_hline(yintercept = 0.8, color = "red", linetype = "dashed", size = 1) +
  geom_vline(xintercept = r_80, color = "darkgreen", linetype = "dashed", size = 1) +
  annotate(
    "text",
    x = r_80,
    y = -0.05,
    label = paste0("r ≈ ", round(r_80, 2)),
    color = "darkgreen",
    angle = 0, 
    hjust = 0.5,
    size = 5
  ) +
  labs(
    x = "Partial correlation (r)",
    y = "Power",
    title = "Power vs Partial Correlation"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    plot.background = element_rect(fill = "white"),
    panel.background = element_rect(fill = "white"),
    plot.title = element_text(face = "bold", hjust = 0.5)
  )


ggsave("power_vs_r.png", plot = p_power, width = 6, height = 5, dpi = 300, bg = "white")
```

```{r}
# plotting: sample size vs correlation
power_target <- 0.8
sample_values <- sapply(r_range, function(r) {
  mlrF.partial(N = NULL, p = k, q = q, pc = r, alpha = alpha, power = power_target)
})

# correlation at sample size = 172
r_eff <- min(r_range[sample_values <= n_eff])

sample_df <- data.frame(
  r = r_range,
  sample_size = sample_values
)

p_sample <- ggplot(sample_df, aes(x = r, y = sample_size)) +
  geom_line(size = 1, color = "blue") +
  geom_hline(yintercept = n_eff, color = "red", linetype = "dashed", size = 1) +
  geom_vline(xintercept = r_eff, color = "darkgreen", linetype = "dashed", size = 1) +
  annotate(
    "text",
    x = r_eff + 0.005,
    y = n_eff + 0, 
    label = paste0("r ≈ ", round(r_eff, 2)),
    color = "darkgreen",
    angle = 0, # vertical
    vjust = 2.5,  # move downward
    hjust = 0.5,
    size = 5
  ) +
  labs(
    x = "Partial correlation (r)",
    y = "Required Sample Size",
    title = "Sample Size vs Partial Correlation (Power = 0.8, k = 8)"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    plot.background = element_rect(fill = "white"),
    panel.background = element_rect(fill = "white"),
    plot.title = element_text(face = "bold", hjust = 0.5)
  )

ggsave("sample_size_vs_r.png", plot = p_sample, width = 6, height = 5, dpi = 300, bg = "white")
```

